name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: csh
      run:  sudo apt install csh
    - name: autoconf
      run:  autoconf
    - name: configure
      run: ./configure --with-yapp=pgplot
    - name: build1
      run: make build1 
    - name: build2
      run: make build2
    - name: build3
      run: make build3
    - name build4
      run: make build4
    - name: make check
      run: make check
